# Generated by Django 4.1.7 on 2023-03-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Codigo de Registro')),
                ('produto', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
                ('medida', models.CharField(choices=[('M', 'Metros (m)'), ('KG', 'Kilos (Kg)'), ('UN', 'Unidades')], max_length=50, verbose_name='Unidade de Medida')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço da unidade (R$)')),
                ('estoque', models.IntegerField(null=True, verbose_name='estoque atual')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
            ],
            options={
                'ordering': ('produto',),
            },
        ),
    ]
