# Generated by Django 4.1.7 on 2023-03-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_lucro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_compra',
        ),
    ]
