# Generated by Django 4.1.7 on 2023-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_lucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='lucro',
            field=models.IntegerField(null=True, verbose_name='Margem de lucro (%)'),
        ),
    ]
