# Generated by Django 4.1.7 on 2023-03-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0004_alter_estoque_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
