# Generated by Django 4.1.7 on 2023-03-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('---', '---'), ('Pessoa Física', 'Pessoa Física'), ('Pessoa Juridica', 'Pessoa Jurídica')], default='---', max_length=50)),
                ('cliente', models.CharField(max_length=50, unique=True, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=50, unique=True, verbose_name='CPF / CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('Tipo_de_inscrição_estadual', models.CharField(choices=[('---', '---'), ('1', 'Contribuinte de ICMS'), ('9', 'Não contribuinte de ICMS'), ('---', 'Contribuinte isento')], default='---', max_length=50)),
                ('rua', models.CharField(max_length=100, null=True, verbose_name='Endereço - Rua')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Nª da casa')),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Endereço - Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Endereço - Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Endereço - Cidade')),
                ('estado', models.CharField(choices=[('---', '---'), ('Acre (AC)', 'Acre (AC)'), ('Alagoas (AL)', 'Alagoas (AL)'), ('Amapá (AP)', 'Amapá (AP)'), ('Amazonas (AM)', 'Amazonas (AM)'), ('Bahia (BA)', 'Bahia (BA)'), ('Ceará (CE)', 'Ceará (CE)'), ('Distrito Federal (DF)', 'Distrito Federal (DF)'), ('Espírito Santo (ES)', 'Espírito Santo (ES)'), ('Goiás (GO)', 'Goiás (GO)'), ('Maranhão (MA)', 'Maranhão (MA)'), ('Mato Grosso (MT)', 'Mato Grosso (MT)'), ('Mato Grosso do Sul (MS)', 'Mato Grosso do Sul (MS)'), ('Minas Gerais (MG)', 'Minas Gerais (MG)'), ('Pará (PA)', 'Pará (PA)'), ('Paraíba (PB)', 'Paraíba (PB)'), ('Paraná (PR)', 'Paraná (PR)'), ('Pernambuco (PE)', 'Pernambuco (PE)'), ('Piauí (PI)', 'Piauí (PI)'), ('Rio de Janeiro (RJ)', 'Rio de Janeiro (RJ)'), ('Rio Grande do Norte (RN)', 'Rio Grande do Norte (RN)'), ('Rio Grande do Sul (RS)', 'Rio Grande do Sul (RS)'), ('Rondônia (RO)', 'Rondônia (RO)'), ('Roraima (RR)', 'Roraima (RR)'), ('Santa Catarina (SC)', 'Santa Catarina (SC)'), ('São Paulo (SP)', 'São Paulo (SP)'), ('Sergipe (SE)', 'Sergipe (SE)'), ('Tocantins (TO)', 'Tocantins (TO)')], default='---', max_length=50, verbose_name='Endereço - Estado')),
                ('cep', models.CharField(max_length=50, verbose_name='Endereço - CEP')),
            ],
            options={
                'ordering': ('cliente',),
            },
        ),
    ]
