# Generated by Django 4.1.7 on 2023-03-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_bairro_remove_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
