# Generated by Django 4.1.7 on 2023-03-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='Tipo_de_inscrição_estadual',
        ),
    ]
