# Generated by Django 4.1.7 on 2023-03-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_remove_fornecedor_bairro_remove_fornecedor_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
    ]
